"""
PDF rendering of the authorization artifacts (SSP / SAR / POA&M).

Renders from the already-built OSCAL dicts (build_oscal_ssp/sar/poam) so there's a
single source of truth — the same content as the Word/OSCAL outputs, just in the
format reviewers usually want. Branding (title color, Prepared by/for) matches the
Word writers. Uses reportlab (pure-Python, no system deps).

Artifacts remain DRAFT; a footer states so on every page.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)


def _brand(hex_color: str):
    h = (hex_color or "").lstrip("#")
    if len(h) == 6:
        try:
            return colors.HexColor("#" + h)
        except ValueError:
            pass
    return colors.HexColor("#0b1020")


def _esc(text) -> str:
    s = "" if text is None else str(text)
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _styles(brand_color: str):
    ss = getSampleStyleSheet()
    accent = _brand(brand_color)
    ss.add(ParagraphStyle("CFTitle", parent=ss["Title"], textColor=accent, fontSize=22))
    ss.add(ParagraphStyle("CFSub", parent=ss["Normal"], alignment=TA_CENTER,
                          textColor=colors.grey, fontSize=10))
    ss.add(ParagraphStyle("CFH1", parent=ss["Heading1"], textColor=accent, fontSize=14))
    ss.add(ParagraphStyle("CFBody", parent=ss["BodyText"], fontSize=9, leading=12))
    return ss


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.grey)
    canvas.drawString(0.75 * inch, 0.5 * inch,
                      "DRAFT — generated by ComplyForge; requires human review. Not an attestation.")
    canvas.drawRightString(7.75 * inch, 0.5 * inch, f"Page {doc.page}")
    canvas.restoreState()


def _header(story, ss, title, system_name, prepared_by, prepared_for):
    story.append(Paragraph(_esc(title), ss["CFTitle"]))
    story.append(Paragraph(_esc(system_name), ss["CFSub"]))
    story.append(Paragraph(f"Version 0.1 (DRAFT) · {_dt.date.today():%d %b %Y}", ss["CFSub"]))
    line = []
    if prepared_for:
        line.append(f"Prepared for: {_esc(prepared_for)}")
    if prepared_by:
        line.append(f"Prepared by: {_esc(prepared_by)}")
    if line:
        story.append(Paragraph("   ·   ".join(line), ss["CFSub"]))
    story.append(Spacer(1, 0.25 * inch))


def _build(path, story):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(str(path), pagesize=letter,
                            topMargin=0.8 * inch, bottomMargin=0.8 * inch)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return path


def _prop(props, name, default=""):
    for p in props or []:
        if p.get("name") == name:
            return p.get("value", default)
    return default


def _table(ss, headers, rows, brand_color, col_widths=None):
    data = [[Paragraph(f"<b>{_esc(h)}</b>", ss["CFBody"]) for h in headers]]
    for r in rows:
        data.append([Paragraph(_esc(c), ss["CFBody"]) for c in r])
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _brand(brand_color)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f3f4f6")]),
    ]))
    return t


# --------------------------------------------------------------------------- #
# Per-artifact renderers (take the OSCAL dict)
# --------------------------------------------------------------------------- #
def ssp_to_pdf(ssp: dict, path, *, prepared_by="", prepared_for="", brand_color="") -> Path:
    s = ssp["system-security-plan"]
    sc = s.get("system-characteristics", {})
    ss = _styles(brand_color)
    story = []
    _header(story, ss, s.get("metadata", {}).get("title", "System Security Plan"),
            sc.get("system-name", ""), prepared_by, prepared_for)

    story.append(Paragraph("1. System Characteristics", ss["CFH1"]))
    impact = (sc.get("security-sensitivity-level")
              or sc.get("security-impact-level", {}).get("security-objective-confidentiality", ""))
    story.append(Paragraph(f"<b>Impact level:</b> {_esc(impact)}", ss["CFBody"]))
    story.append(Paragraph(f"<b>Description:</b> {_esc(sc.get('description', ''))}", ss["CFBody"]))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("2. Control Implementation", ss["CFH1"]))
    irs = s.get("control-implementation", {}).get("implemented-requirements", [])
    rows = []
    for ir in irs:
        status = _prop(ir.get("props"), "implementation-status")
        review = _prop(ir.get("props"), "review-status")
        prose = ""
        for bc in ir.get("by-components", []):
            prose = bc.get("description", "") or prose
        rows.append([(ir.get("control-id", "") or "").upper(), status,
                     "needs review" if "needs-review" in review else "reviewed",
                     prose])
    if rows:
        story.append(_table(ss, ["Control", "Status", "Review", "Implementation statement"],
                            rows, brand_color,
                            col_widths=[0.8 * inch, 0.8 * inch, 0.8 * inch, 4.3 * inch]))
    else:
        story.append(Paragraph("No controls documented yet.", ss["CFBody"]))
    return _build(path, story)


def sar_to_pdf(sar: dict, path, *, prepared_by="", prepared_for="", brand_color="") -> Path:
    a = sar["assessment-results"]
    res = (a.get("results") or [{}])[0]
    ss = _styles(brand_color)
    story = []
    _header(story, ss, a.get("metadata", {}).get("title", "Security Assessment Report"),
            "", prepared_by, prepared_for)
    story.append(Paragraph("1. Summary", ss["CFH1"]))
    story.append(Paragraph(_esc(res.get("description", "")), ss["CFBody"]))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("2. Findings", ss["CFH1"]))
    findings = res.get("findings", [])
    if findings:
        rows = [[_prop(f.get("props"), "control-id").upper(),
                 _prop(f.get("props"), "finding-source"),
                 f.get("description", "")] for f in findings]
        story.append(_table(ss, ["Control", "Source", "Finding"], rows, brand_color,
                            col_widths=[0.9 * inch, 1.1 * inch, 4.7 * inch]))
    else:
        story.append(Paragraph("No findings — all assessed controls satisfied.", ss["CFBody"]))
    return _build(path, story)


def poam_to_pdf(poam: dict, path, *, prepared_by="", prepared_for="", brand_color="") -> Path:
    p = poam["plan-of-action-and-milestones"]
    ss = _styles(brand_color)
    story = []
    _header(story, ss, p.get("metadata", {}).get("title", "Plan of Action & Milestones"),
            "", prepared_by, prepared_for)
    items = p.get("poam-items", [])
    story.append(Paragraph(f"{len(items)} POA&M item(s)", ss["CFH1"]))
    if items:
        rows = [[_prop(it.get("props"), "control-id").upper(),
                 _prop(it.get("props"), "poam-status"),
                 it.get("description", "")] for it in items]
        story.append(_table(ss, ["Control", "Status", "Weakness"], rows, brand_color,
                            col_widths=[0.9 * inch, 1.0 * inch, 4.8 * inch]))
    else:
        story.append(Paragraph("No open items.", ss["CFBody"]))
    return _build(path, story)
